packages:
  - apps/*
  - packages/*

overrides:
  "@types/node": 24.13.1
  form-data@4.0.5: 4.0.6
  undici@6.26.0: 6.27.0
  undici@7.27.1: 7.28.0

supportedArchitectures:
  os:
    - darwin
    - win32
  cpu:
    - arm64
    - x64

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - electron
  - electron-builder
  - electron-winstaller
  - esbuild
  - sharp
