packages:
  - apps/*
  - packages/*

overrides:
  "@types/node": 24.13.1

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm64
    - x64

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - "@yao-pkg/pkg"
  - electron
  - electron-builder
  - electron-winstaller
  - esbuild
  - sharp

minimumReleaseAgeExclude:
  - electron@42.4.0
