#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CliCommandPolicy {
    Local,
    Observe,
    Activate,
    Stop,
    Run,
    Submit,
    Stream,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CliOptionKind {
    Value,
    Flag,
    Repeatable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CliOptionSpec {
    pub name: &'static str,
    pub kind: CliOptionKind,
    pub required: bool,
    pub project_path: bool,
    pub allowed_values: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CliCommandSpec {
    pub command: &'static str,
    pub path: &'static [&'static str],
    pub policy: CliCommandPolicy,
    pub scope: &'static str,
    pub risk: &'static str,
    pub requires: &'static str,
    pub writes: &'static str,
    pub input: &'static str,
    pub output: &'static str,
    pub minimum_positionals: usize,
    pub maximum_positionals: usize,
    pub project_positional: Option<usize>,
    pub options: &'static [CliOptionSpec],
    pub errors: &'static [&'static str],
}

const NO_OPTIONS: &[CliOptionSpec] = &[];
const WORKBENCH_OPTIONS: &[CliOptionSpec] = &[option(
    "frontend",
    CliOptionKind::Value,
    false,
    false,
    &["default", "desktop", "browser"],
)];
const RESET_LAYOUT_OPTIONS: &[CliOptionSpec] = &[
    option("all", CliOptionKind::Flag, false, false, &[]),
    option("path", CliOptionKind::Repeatable, false, false, &[]),
    option("glob", CliOptionKind::Repeatable, false, false, &[]),
];
const GENERATED_ASSET_OPTIONS: &[CliOptionSpec] =
    &[option("path", CliOptionKind::Value, true, false, &[])];
const REQUEST_SINGLE_OPTIONS: &[CliOptionSpec] = &[
    option("input", CliOptionKind::Value, true, false, &[]),
    option("timeout", CliOptionKind::Value, false, false, &[]),
    option("replace", CliOptionKind::Flag, false, false, &[]),
    option("no-wait", CliOptionKind::Flag, false, false, &[]),
];
const REQUEST_BATCH_OPTIONS: &[CliOptionSpec] = &[
    option("input", CliOptionKind::Value, true, false, &[]),
    option("concurrency", CliOptionKind::Value, false, false, &[]),
    option("timeout", CliOptionKind::Value, false, false, &[]),
    option("replace", CliOptionKind::Flag, false, false, &[]),
    option("no-wait", CliOptionKind::Flag, false, false, &[]),
];
const OPERATION_LIST_OPTIONS: &[CliOptionSpec] = &[
    option(
        "state",
        CliOptionKind::Value,
        false,
        false,
        &[
            "active",
            "terminal",
            "queued",
            "running",
            "cancelling",
            "succeeded",
            "failed",
            "cancelled",
        ],
    ),
    option(
        "model-kind",
        CliOptionKind::Value,
        false,
        false,
        &["image", "video", "tts", "music", "sound-effect"],
    ),
    option("project", CliOptionKind::Value, false, true, &[]),
    option("limit", CliOptionKind::Value, false, false, &[]),
    option("cursor", CliOptionKind::Value, false, false, &[]),
];
const RUNTIME_CONFIG_ERRORS: &[&str] = &["runtime_config_error"];
const AUDIO_MODEL_ERRORS: &[&str] = &[
    "audio_model_unavailable",
    "audio_model_kind_mismatch",
    "runtime_config_error",
];
const PROJECT_READ_ERRORS: &[&str] = &["project_not_found", "project_invalid"];
const CANVAS_REGISTRY_ERRORS: &[&str] = &[
    "project_not_found",
    "project_invalid",
    "canvas_registry_missing",
    "canvas_registry_invalid",
    "canvas_registry_conflict",
    "canvas_registry_repair_failed",
    "canvas_map_conflict",
];
const MODEL_REQUEST_ERRORS: &[&str] = &[
    "project_invalid",
    "model_unavailable",
    "submission_outcome_unknown",
    "runtime_lost",
];
const OPERATION_OBSERVE_ERRORS: &[&str] = &[
    "operation_not_found",
    "operation_failed",
    "operation_cancelled",
    "runtime_lost",
];
const OBSERVE_ERRORS: &[&str] = &[
    "runtime_ready_timeout",
    "runtime_health_failed",
    "runtime_lost",
    "product_update_failed",
];
const ACTIVATE_ERRORS: &[&str] = &[
    "runtime_launch_failed",
    "runtime_ready_timeout",
    "runtime_health_failed",
    "product_update_failed",
];
const STOP_ERRORS: &[&str] = &[
    "runtime_not_running",
    "runtime_health_failed",
    "product_update_failed",
];
const RUNTIME_COMMAND_ERRORS: &[&str] = &[
    "runtime_launch_failed",
    "runtime_ready_timeout",
    "runtime_health_failed",
    "runtime_lost",
    "product_update_failed",
];

const fn option(
    name: &'static str,
    kind: CliOptionKind,
    required: bool,
    project_path: bool,
    allowed_values: &'static [&'static str],
) -> CliOptionSpec {
    CliOptionSpec {
        name,
        kind,
        required,
        project_path,
        allowed_values,
    }
}

const SPECS: &[CliCommandSpec] = &[
    spec(
        "update",
        &["update"],
        CliCommandPolicy::Run,
        "runtime",
        "write",
        "none",
        "logs",
        "no args",
        "product update record",
        0,
        0,
        None,
        NO_OPTIONS,
        &["product_update_unavailable"],
    ),
    spec(
        "runtime.status",
        &["runtime", "status"],
        CliCommandPolicy::Observe,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "runtime status record",
        0,
        0,
        None,
        NO_OPTIONS,
        &[],
    ),
    spec(
        "runtime.doctor",
        &["runtime", "doctor"],
        CliCommandPolicy::Observe,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "diagnostic records",
        0,
        0,
        None,
        NO_OPTIONS,
        RUNTIME_CONFIG_ERRORS,
    ),
    spec(
        "runtime.stop",
        &["runtime", "stop"],
        CliCommandPolicy::Stop,
        "runtime",
        "destructive",
        "running-runtime",
        "runtime-lifecycle",
        "no args",
        "accepted Product Quit record",
        0,
        0,
        None,
        NO_OPTIONS,
        &[],
    ),
    spec(
        "skills.status",
        &["skills", "status"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "Runtime-owned Skills diagnostic",
        0,
        0,
        None,
        NO_OPTIONS,
        &[
            "skills_bundle_unavailable",
            "skills_bundle_invalid",
            "skills_state_unreadable",
        ],
    ),
    spec(
        "models.image.list",
        &["models", "image", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "image model records",
        0,
        0,
        None,
        NO_OPTIONS,
        RUNTIME_CONFIG_ERRORS,
    ),
    spec(
        "models.image.describe",
        &["models", "image", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "image model detail record",
        1,
        1,
        None,
        NO_OPTIONS,
        &["model_unavailable", "runtime_config_error"],
    ),
    spec(
        "models.video.list",
        &["models", "video", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "video model records",
        0,
        0,
        None,
        NO_OPTIONS,
        RUNTIME_CONFIG_ERRORS,
    ),
    spec(
        "models.video.describe",
        &["models", "video", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "video model detail record",
        1,
        1,
        None,
        NO_OPTIONS,
        &["model_unavailable", "runtime_config_error"],
    ),
    spec(
        "models.tts.list",
        &["models", "tts", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "TTS model records",
        0,
        0,
        None,
        NO_OPTIONS,
        RUNTIME_CONFIG_ERRORS,
    ),
    spec(
        "models.tts.describe",
        &["models", "tts", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "TTS model detail record",
        1,
        1,
        None,
        NO_OPTIONS,
        AUDIO_MODEL_ERRORS,
    ),
    spec(
        "models.music.list",
        &["models", "music", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "music model records",
        0,
        0,
        None,
        NO_OPTIONS,
        RUNTIME_CONFIG_ERRORS,
    ),
    spec(
        "models.music.describe",
        &["models", "music", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "music model detail record",
        1,
        1,
        None,
        NO_OPTIONS,
        AUDIO_MODEL_ERRORS,
    ),
    spec(
        "models.sfx.list",
        &["models", "sfx", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "sound effect model records",
        0,
        0,
        None,
        NO_OPTIONS,
        RUNTIME_CONFIG_ERRORS,
    ),
    spec(
        "models.sfx.describe",
        &["models", "sfx", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "sound effect model detail record",
        1,
        1,
        None,
        NO_OPTIONS,
        AUDIO_MODEL_ERRORS,
    ),
    spec(
        "project.init",
        &["project", "init"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "debrute-project",
        "<project>",
        "project status record",
        1,
        1,
        Some(0),
        NO_OPTIONS,
        &["project_invalid"],
    ),
    spec(
        "project.status",
        &["project", "status"],
        CliCommandPolicy::Run,
        "project",
        "read",
        "project",
        "none",
        "<project>",
        "project status record",
        1,
        1,
        Some(0),
        NO_OPTIONS,
        PROJECT_READ_ERRORS,
    ),
    spec(
        "project.validate",
        &["project", "validate"],
        CliCommandPolicy::Run,
        "project",
        "read",
        "project",
        "none",
        "<project>",
        "validation problem records",
        1,
        1,
        Some(0),
        NO_OPTIONS,
        &[
            "project_not_found",
            "project_invalid",
            "project_validation_failed",
        ],
    ),
    spec(
        "workbench.start",
        &["workbench", "start"],
        CliCommandPolicy::Activate,
        "runtime",
        "write",
        "none",
        "none",
        "[<project>] [--frontend default|desktop|browser]",
        "accepted frontend and target record",
        0,
        1,
        Some(0),
        WORKBENCH_OPTIONS,
        &[],
    ),
    spec(
        "canvas-map.push",
        &["canvas-map", "push"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-map",
        "<project> <canvas-id>",
        "Canvas Map push record",
        2,
        2,
        Some(0),
        NO_OPTIONS,
        &[
            "project_not_found",
            "project_invalid",
            "canvas_map_invalid_canvas_id",
            "canvas_map_invalid_path",
            "canvas_map_layout_conflict",
            "canvas_map_read_failed",
            "canvas_map_invalid_yaml",
            "canvas_map_canvas_missing",
        ],
    ),
    spec(
        "canvas.create",
        &["canvas", "create"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project>",
        "Canvas create record",
        1,
        1,
        Some(0),
        NO_OPTIONS,
        CANVAS_REGISTRY_ERRORS,
    ),
    spec(
        "canvas.rename",
        &["canvas", "rename"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project> <canvas-id> <name>",
        "Canvas rename record",
        3,
        3,
        Some(0),
        NO_OPTIONS,
        CANVAS_REGISTRY_ERRORS,
    ),
    spec(
        "canvas.delete",
        &["canvas", "delete"],
        CliCommandPolicy::Run,
        "project",
        "destructive",
        "project",
        "canvas-registry",
        "<project> <canvas-id>",
        "Canvas delete record",
        2,
        2,
        Some(0),
        NO_OPTIONS,
        CANVAS_REGISTRY_ERRORS,
    ),
    spec(
        "canvas.reorder",
        &["canvas", "reorder"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project> <canvas-id...>",
        "Canvas reorder record",
        2,
        usize::MAX,
        Some(0),
        NO_OPTIONS,
        CANVAS_REGISTRY_ERRORS,
    ),
    spec(
        "canvas.repair-index",
        &["canvas", "repair-index"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project>",
        "Canvas registry repair record",
        1,
        1,
        Some(0),
        NO_OPTIONS,
        CANVAS_REGISTRY_ERRORS,
    ),
    spec(
        "canvas.reset-layout",
        &["canvas", "reset-layout"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-map",
        "<project> <canvas-id> --all | <project> <canvas-id> [--path <literal...>] [--glob <pattern...>]",
        "Canvas layout reset record",
        2,
        2,
        Some(0),
        RESET_LAYOUT_OPTIONS,
        &[
            "project_not_found",
            "project_invalid",
            "canvas_registry_missing",
            "canvas_registry_invalid",
            "canvas_registry_conflict",
            "canvas_registry_repair_failed",
            "canvas_map_conflict",
            "canvas_map_invalid_path",
            "canvas_map_invalid_yaml",
            "canvas_map_canvas_missing",
        ],
    ),
    spec(
        "generated-asset.lookup",
        &["generated-asset", "lookup"],
        CliCommandPolicy::Run,
        "project",
        "read",
        "project",
        "none",
        "<project> --path <project-relative-path>",
        "generated asset metadata record",
        1,
        1,
        Some(0),
        GENERATED_ASSET_OPTIONS,
        PROJECT_READ_ERRORS,
    ),
    spec(
        "request.single",
        &["request", "single"],
        CliCommandPolicy::Submit,
        "model-operation",
        "execute",
        "project",
        "assets",
        "<project> --input <request.jsonl|-> [--timeout <Ns|Nm|Nh>] [--replace] [--no-wait]",
        "accepted or terminal Model Operation record",
        1,
        1,
        Some(0),
        REQUEST_SINGLE_OPTIONS,
        MODEL_REQUEST_ERRORS,
    ),
    spec(
        "request.batch",
        &["request", "batch"],
        CliCommandPolicy::Submit,
        "model-operation",
        "execute",
        "project",
        "assets",
        "<project> --input <requests.jsonl|-> [--concurrency <n>] [--timeout <Ns|Nm|Nh>] [--replace] [--no-wait]",
        "accepted, Item outcome, and terminal Model Operation records",
        1,
        1,
        Some(0),
        REQUEST_BATCH_OPTIONS,
        MODEL_REQUEST_ERRORS,
    ),
    spec(
        "operation.list",
        &["operation", "list"],
        CliCommandPolicy::Run,
        "model-operation",
        "read",
        "runtime",
        "none",
        "[--state <state>] [--model-kind <kind>] [--project <path>] [--limit <1..100>] [--cursor <cursor>]",
        "current Runtime Model Operation records",
        0,
        0,
        None,
        OPERATION_LIST_OPTIONS,
        &["invalid_cursor", "runtime_lost"],
    ),
    spec(
        "operation.inspect",
        &["operation", "inspect"],
        CliCommandPolicy::Run,
        "model-operation",
        "read",
        "runtime",
        "none",
        "<operation-id>",
        "current Model Operation record",
        1,
        1,
        None,
        NO_OPTIONS,
        OPERATION_OBSERVE_ERRORS,
    ),
    spec(
        "operation.wait",
        &["operation", "wait"],
        CliCommandPolicy::Stream,
        "model-operation",
        "read",
        "runtime",
        "none",
        "<operation-id>",
        "Item outcomes and terminal Model Operation record",
        1,
        1,
        None,
        NO_OPTIONS,
        OPERATION_OBSERVE_ERRORS,
    ),
    spec(
        "operation.cancel",
        &["operation", "cancel"],
        CliCommandPolicy::Run,
        "model-operation",
        "write",
        "runtime",
        "operation-state",
        "<operation-id>",
        "latest Model Operation record",
        1,
        1,
        None,
        NO_OPTIONS,
        &[
            "operation_not_found",
            "operation_already_terminal",
            "runtime_lost",
        ],
    ),
    spec(
        "commands",
        &["commands"],
        CliCommandPolicy::Local,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "command spec records",
        0,
        0,
        None,
        NO_OPTIONS,
        &[],
    ),
    spec(
        "help",
        &["help"],
        CliCommandPolicy::Local,
        "runtime",
        "read",
        "none",
        "none",
        "<command-path>",
        "one command spec record",
        1,
        3,
        None,
        NO_OPTIONS,
        &[],
    ),
];

#[allow(clippy::too_many_arguments)]
const fn spec(
    command: &'static str,
    path: &'static [&'static str],
    policy: CliCommandPolicy,
    scope: &'static str,
    risk: &'static str,
    requires: &'static str,
    writes: &'static str,
    input: &'static str,
    output: &'static str,
    minimum_positionals: usize,
    maximum_positionals: usize,
    project_positional: Option<usize>,
    options: &'static [CliOptionSpec],
    errors: &'static [&'static str],
) -> CliCommandSpec {
    CliCommandSpec {
        command,
        path,
        policy,
        scope,
        risk,
        requires,
        writes,
        input,
        output,
        minimum_positionals,
        maximum_positionals,
        project_positional,
        options,
        errors,
    }
}

#[must_use]
pub const fn command_specs() -> &'static [CliCommandSpec] {
    SPECS
}

#[must_use]
pub fn command_spec(path: &[String]) -> Option<&'static CliCommandSpec> {
    SPECS.iter().find(|spec| {
        spec.path.len() == path.len()
            && spec
                .path
                .iter()
                .zip(path)
                .all(|(expected, actual)| *expected == actual)
    })
}

#[must_use]
pub fn command_errors(command: &str) -> String {
    let mut errors = vec![
        "invalid_command",
        "invalid_argument",
        "missing_argument",
        "invalid_input",
        "internal_error",
    ];
    if let Some(spec) = SPECS.iter().find(|spec| spec.command == command) {
        for error in policy_errors(spec.policy).iter().chain(spec.errors) {
            if !errors.contains(error) {
                errors.push(error);
            }
        }
    }
    errors.join(",")
}

const fn policy_errors(policy: CliCommandPolicy) -> &'static [&'static str] {
    match policy {
        CliCommandPolicy::Local => &[],
        CliCommandPolicy::Observe => OBSERVE_ERRORS,
        CliCommandPolicy::Activate => ACTIVATE_ERRORS,
        CliCommandPolicy::Stop => STOP_ERRORS,
        CliCommandPolicy::Run | CliCommandPolicy::Submit | CliCommandPolicy::Stream => {
            RUNTIME_COMMAND_ERRORS
        }
    }
}
