#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CliCommandPolicy {
    Local,
    Observe,
    Activate,
    Stop,
    Run,
    Stream,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CliCommandSpec {
    pub command: &'static str,
    pub path: &'static [&'static str],
    pub policy: CliCommandPolicy,
    pub scope: &'static str,
    pub risk: &'static str,
    pub requires: &'static str,
    pub writes: &'static str,
    pub input: &'static str,
    pub output: &'static str,
}

const SPECS: &[CliCommandSpec] = &[
    spec(
        "update",
        &["update"],
        CliCommandPolicy::Run,
        "runtime",
        "write",
        "none",
        "logs",
        "no args",
        "product update record",
    ),
    spec(
        "runtime.status",
        &["runtime", "status"],
        CliCommandPolicy::Observe,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "runtime status record",
    ),
    spec(
        "runtime.doctor",
        &["runtime", "doctor"],
        CliCommandPolicy::Observe,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "diagnostic records",
    ),
    spec(
        "runtime.stop",
        &["runtime", "stop"],
        CliCommandPolicy::Stop,
        "runtime",
        "destructive",
        "running-runtime",
        "runtime-lifecycle",
        "no args",
        "accepted Product Quit record",
    ),
    spec(
        "skills.status",
        &["skills", "status"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "Runtime-owned Skills diagnostic",
    ),
    spec(
        "models.image.list",
        &["models", "image", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "image model records",
    ),
    spec(
        "models.image.describe",
        &["models", "image", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "image model detail record",
    ),
    spec(
        "models.video.list",
        &["models", "video", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "video model records",
    ),
    spec(
        "models.video.describe",
        &["models", "video", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "video model detail record",
    ),
    spec(
        "models.tts.list",
        &["models", "tts", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "TTS model records",
    ),
    spec(
        "models.tts.describe",
        &["models", "tts", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "TTS model detail record",
    ),
    spec(
        "models.music.list",
        &["models", "music", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "music model records",
    ),
    spec(
        "models.music.describe",
        &["models", "music", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "music model detail record",
    ),
    spec(
        "models.sfx.list",
        &["models", "sfx", "list"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "no args",
        "sound effect model records",
    ),
    spec(
        "models.sfx.describe",
        &["models", "sfx", "describe"],
        CliCommandPolicy::Run,
        "runtime",
        "read",
        "model-config",
        "none",
        "<model-id>",
        "sound effect model detail record",
    ),
    spec(
        "project.init",
        &["project", "init"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "debrute-project",
        "<project>",
        "project status record",
    ),
    spec(
        "project.status",
        &["project", "status"],
        CliCommandPolicy::Run,
        "project",
        "read",
        "project",
        "none",
        "<project>",
        "project status record",
    ),
    spec(
        "project.validate",
        &["project", "validate"],
        CliCommandPolicy::Run,
        "project",
        "read",
        "project",
        "none",
        "<project>",
        "validation problem records",
    ),
    spec(
        "workbench.start",
        &["workbench", "start"],
        CliCommandPolicy::Activate,
        "runtime",
        "write",
        "none",
        "none",
        "[<project>] [--frontend default|desktop|browser]",
        "accepted frontend and target record",
    ),
    spec(
        "canvas-map.push",
        &["canvas-map", "push"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-map",
        "<project> <canvas-id>",
        "Canvas Map push record",
    ),
    spec(
        "canvas.create",
        &["canvas", "create"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project>",
        "Canvas create record",
    ),
    spec(
        "canvas.rename",
        &["canvas", "rename"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project> <canvas-id> <name>",
        "Canvas rename record",
    ),
    spec(
        "canvas.delete",
        &["canvas", "delete"],
        CliCommandPolicy::Run,
        "project",
        "destructive",
        "project",
        "canvas-registry",
        "<project> <canvas-id>",
        "Canvas delete record",
    ),
    spec(
        "canvas.reorder",
        &["canvas", "reorder"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project> <canvas-id...>",
        "Canvas reorder record",
    ),
    spec(
        "canvas.repair-index",
        &["canvas", "repair-index"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-registry",
        "<project>",
        "Canvas registry repair record",
    ),
    spec(
        "canvas.reset-layout",
        &["canvas", "reset-layout"],
        CliCommandPolicy::Run,
        "project",
        "write",
        "project",
        "canvas-map",
        "<project> <canvas-id> --all | <project> <canvas-id> [--path <literal...>] [--glob <pattern...>]",
        "Canvas layout reset record",
    ),
    spec(
        "generated-asset.lookup",
        &["generated-asset", "lookup"],
        CliCommandPolicy::Run,
        "project",
        "read",
        "project",
        "none",
        "<project> --path <project-relative-path>",
        "generated asset metadata record",
    ),
    spec(
        "generate.image",
        &["generate", "image"],
        CliCommandPolicy::Run,
        "generation",
        "generate",
        "project-session",
        "assets",
        "<project> --input-json <json> [--timeout-ms <ms>]",
        "generated image artifact records",
    ),
    spec(
        "generate.image-batch",
        &["generate", "image-batch"],
        CliCommandPolicy::Stream,
        "generation",
        "generate",
        "project-session",
        "assets",
        "<project> (--manifest <path> | --input-jsonl <path>) --log <path> [--summary <path>] [--concurrency <n>] [--timeout-ms <ms>] [--overwrite-existing]",
        "batch progress and summary records",
    ),
    spec(
        "generate.video",
        &["generate", "video"],
        CliCommandPolicy::Run,
        "generation",
        "generate",
        "project-session",
        "assets",
        "<project> --input-json <json> [--timeout-ms <ms>]",
        "generated video artifact records",
    ),
    spec(
        "generate.tts",
        &["generate", "tts"],
        CliCommandPolicy::Run,
        "generation",
        "generate",
        "project-session",
        "assets",
        "<project> --input-json <json> [--timeout-ms <ms>]",
        "generated TTS artifact records",
    ),
    spec(
        "generate.music",
        &["generate", "music"],
        CliCommandPolicy::Run,
        "generation",
        "generate",
        "project-session",
        "assets",
        "<project> --input-json <json> [--timeout-ms <ms>]",
        "generated music artifact records",
    ),
    spec(
        "generate.sfx",
        &["generate", "sfx"],
        CliCommandPolicy::Run,
        "generation",
        "generate",
        "project-session",
        "assets",
        "<project> --input-json <json> [--timeout-ms <ms>]",
        "generated sound effect artifact records",
    ),
    spec(
        "commands",
        &["commands"],
        CliCommandPolicy::Local,
        "runtime",
        "read",
        "none",
        "none",
        "no args",
        "command spec records",
    ),
    spec(
        "help",
        &["help"],
        CliCommandPolicy::Local,
        "runtime",
        "read",
        "none",
        "none",
        "<command-path>",
        "one command spec record",
    ),
];

#[allow(clippy::too_many_arguments)]
const fn spec(
    command: &'static str,
    path: &'static [&'static str],
    policy: CliCommandPolicy,
    scope: &'static str,
    risk: &'static str,
    requires: &'static str,
    writes: &'static str,
    input: &'static str,
    output: &'static str,
) -> CliCommandSpec {
    CliCommandSpec {
        command,
        path,
        policy,
        scope,
        risk,
        requires,
        writes,
        input,
        output,
    }
}

#[must_use]
pub const fn command_specs() -> &'static [CliCommandSpec] {
    SPECS
}

#[must_use]
pub fn command_spec(path: &[String]) -> Option<&'static CliCommandSpec> {
    SPECS.iter().find(|spec| {
        spec.path.len() == path.len()
            && spec
                .path
                .iter()
                .zip(path)
                .all(|(expected, actual)| *expected == actual)
    })
}

#[must_use]
pub fn command_errors(command: &str) -> String {
    let mut errors = vec![
        "invalid_command",
        "invalid_argument",
        "missing_argument",
        "invalid_input",
        "internal_error",
    ];
    errors.extend_from_slice(match command {
        "update" => &[
            "runtime_launch_failed",
            "runtime_health_failed",
            "product_update_failed",
        ],
        "runtime.doctor" | "models.image.list" | "models.video.list" | "models.tts.list"
        | "models.music.list" | "models.sfx.list" => &["runtime_config_error"],
        "skills.status" => &[
            "skills_bundle_unavailable",
            "skills_bundle_invalid",
            "skills_state_unreadable",
        ],
        "models.image.describe" | "models.video.describe" => {
            &["model_unavailable", "runtime_config_error"]
        }
        "models.tts.describe" | "models.music.describe" | "models.sfx.describe" => &[
            "audio_model_unavailable",
            "audio_model_kind_mismatch",
            "runtime_config_error",
        ],
        "project.init" => &["project_invalid"],
        "project.status" | "generated-asset.lookup" => &["project_not_found", "project_invalid"],
        "project.validate" => &[
            "project_not_found",
            "project_invalid",
            "project_validation_failed",
        ],
        "canvas-map.push" => &[
            "project_not_found",
            "project_invalid",
            "canvas_map_invalid_canvas_id",
            "canvas_map_invalid_path",
            "canvas_map_layout_conflict",
            "canvas_map_read_failed",
            "canvas_map_invalid_yaml",
            "canvas_map_canvas_missing",
        ],
        "canvas.create"
        | "canvas.rename"
        | "canvas.delete"
        | "canvas.reorder"
        | "canvas.repair-index" => &[
            "project_not_found",
            "project_invalid",
            "canvas_registry_missing",
            "canvas_registry_invalid",
            "canvas_registry_conflict",
            "canvas_registry_repair_failed",
            "canvas_map_conflict",
        ],
        "canvas.reset-layout" => &[
            "project_not_found",
            "project_invalid",
            "canvas_registry_missing",
            "canvas_registry_invalid",
            "canvas_registry_conflict",
            "canvas_registry_repair_failed",
            "canvas_map_conflict",
            "canvas_map_invalid_path",
            "canvas_map_invalid_yaml",
            "canvas_map_canvas_missing",
        ],
        "generate.image" | "generate.video" | "generate.image-batch" => &[
            "project_not_found",
            "project_invalid",
            "invalid_json_input",
            "model_not_configured",
            "model_unavailable",
            "model_request_failed",
        ],
        "generate.tts" | "generate.music" | "generate.sfx" => &[
            "project_not_found",
            "project_invalid",
            "invalid_json_input",
            "audio_model_not_configured",
            "audio_model_unavailable",
            "audio_model_kind_mismatch",
            "audio_argument_invalid",
            "audio_request_failed",
            "audio_artifact_download_failed",
            "audio_task_failed",
            "audio_task_timeout",
        ],
        "workbench.start" => &[
            "runtime_launch_failed",
            "runtime_health_failed",
            "invalid_activation",
            "desktop_unavailable",
        ],
        _ => &[],
    });
    errors.join(",")
}
